[template]
sub_templates = ["contracts"]
ignore = [ 
  "contracts/cw-minimal-template",
  "contracts/cw-sylvia-template",
  "contracts/cw20-base",
  "contracts/cw721-base",
  "contracts/pre-script.rhai",
]
